export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const UPDATE_USER = "UPDATE_USER";
export const ADD_SNIPPET = "ADD_SNIPPET";

export const GET_SUBMISSION = "GET_SUBMISSION";
export const NEW_SUBMISSION = "NEW_SUBMISSION";
export const FETCH_SUBMISSION_ERROR = "FETCH_SUBMISSION_ERROR";
export const RESET_SUBMISSION = "RESET_SUBMISSION";

export const UPDATE_TAB = "UPDATE_TAB";
export const RESET_TAB = "RESET_TAB";

export const ADD_ALERT = "ADD_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
